language: node_js

node_js:
  - 8

script:
  - npm test

notifications:
   email:
    recipients:
      - sophienanterre@gmail.com
      
    on_success: always # default: change
    on_failure: always # default: always
